# roles/nginx/tasks/main.yml

# Available Packages
# Name        : nginx
# Arch        : x86_64
# Epoch       : 1
# Version     : 1.10.3
# Release     : 1.el7.ngx
# Size        : 2.3 M
# Repo        : installed
# From repo   : nginx
# Summary     : High performance web server
# URL         : http://nginx.org/
# License     : 2-clause BSD-like license
# Description : nginx [engine x] is an HTTP and reverse proxy server, as well as
#             : a mail proxy server.

- name: add repository
  template: src=roles/nginx/templates/nginx.repo dest=/etc/yum.repos.d/nginx.repo
  tags: nginx

- name: yum install nginx
  yum: name=nginx state=present
  tags: nginx

- name: service nginx start
  service: name=nginx state=started enabled=yes
  tags: nginx

- name: put reverse_proxy.conf
  template: src=roles/nginx/templates/reverse_proxy.conf dest=/etc/nginx/conf.d/reverse_proxy.conf
  tags: nginx

- name: service nginx restart
  service: name=nginx state=restarted enabled=yes
  tags: nginx
