# roles/mysql57/tasks/main.yml
# https://github.com/geerlingguy/ansible-role-mysql

- name: add repository
  shell: rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
  args:
    creates: /etc/yum.repos.d/mysql-community.repo
  tags: mysql57

- name: check repository exists
  stat:
    path: /etc/yum.repos.d/mysql-community.repo
  register: mysql_repo
  tags: mysql57

- name: yum install mysql-community-server
  yum:
    name: mysql-community-server
    state: present
  when: mysql_repo.stat.exists == true
  tags: mysql57

- name: start server
  service:
    name: mysqld
    state: started
    enabled: yes
  tags: mysql57
